-- Database: GLOBALPLA Metadata version: 2 Exported: Sep 22, 2020
-- Begin Tables
SET LEGACYTYPESALLOWED = ON;
-- Begin Multi-Line Statement
CREATE TABLE "GCG_6113_AR_AGING_DASH" (
 "CUSTOMER" CHAR(6),
 "NAME_CUSTOMER" CHAR(30),
 "SALESPERSON" CHAR(30),
 "BRANCH" CHAR(2),
 "INVOICE" CHAR(7),
 "DATE_INVOICE" DATE,
 "DATE_TRANSACTION" DATE,
 "DUE_DATE" DATE,
 "TYPE" CHAR(20),
 "REFERENCE" CHAR(22),
 "AMT_INVOICE" NUMERIC(16,2),
 "CURRENT1" DOUBLE,
 "TPD2" DOUBLE,
 "TPD3" DOUBLE,
 "OVER" DOUBLE,
 "NOT_AGED" DOUBLE,
 "COLUMN1" CHAR(50),
 "ADJUST" CHAR(6),
 "PAY" CHAR(50),
 "CUSTINV" CHAR(13),
 "SALES_ORDER" CHAR(11),
 "EMAIL" LONGVARCHAR,
 "TELEPHONE" CHAR(20),
 "ZERO" NUMERIC(16,2),
 "AGE_CASH" BIT NOT NULL,
 "AGE_CASH2" BIT NOT NULL,
 "AGE_CASH3" BIT NOT NULL,
 "OVER2" NUMERIC(16,2) );
-- End Multi-Line Statement
SET LEGACYTYPESALLOWED = OFF;
-- End Tables
